#!/usr/bin/env bash
# Installs nginx, configures a redirect and a custom 404 page

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html
echo -n "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}"

echo "$new_config" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
